import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import type { inferProcedureOutput } from "@trpc/server";
import type { AppRouter } from "@acme/api";
import { useAuth, UserButton } from "@clerk/nextjs";
import Link from "next/link";
import Image from "next/image";

const PostCard: React.FC<{
  post: inferProcedureOutput<AppRouter["post"]["all"]>[number];
}> = ({ post }) => {
  return (
    <div className="max-w-2xl rounded-lg border-2 border-gray-500 p-4 transition-all hover:scale-[101%]">
      <h2 className="text-2xl font-bold text-[hsl(280,100%,70%)]">
        {post.title}
      </h2>
      <p>{post.content}</p>
    </div>
  );
};

const Home: NextPage = () => {
  const postQuery = trpc.post.all.useQuery();

  return (
    <>
      <Head>
        <title>vanvee</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen flex-col items-center bg-gradient-to-b from-[#3da7ee] to-[#1821d2] text-white">
        <div className="container mx-12 flex flex-col items-center justify-center gap-12 px-4 py-8">
          <div className="flex gap-12">
            <h1 className="text-5xl font-extrabold tracking-tight sm:text-[5rem]">
              take a spin with{" "}
              <span className="bg-gradient-to-r from-[#c1233b] to-[#4831db] bg-clip-text text-transparent">
                vanvee
              </span>
              .
            </h1>
            <AuthShowcase />
          </div>

          <div className="flex justify-center overflow-y-scroll text-2xl">
            {postQuery.data ? (
              <div className="flex flex-col gap-4">
                {postQuery.data?.map((p) => {
                  return <PostCard key={p.id} post={p} />;
                })}
              </div>
            ) : (
              <p>Loading..</p>
            )}
          </div>

          <Image
            src="/images/vanvee.webp"
            width={500}
            height={500}
            alt="vanvee logo"
          />
        </div>
        <footer className="absolute bottom-0 p-2 font-extrabold tracking-tight">
          vanvee | 2023
        </footer>
      </main>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { isSignedIn } = useAuth();
  const { data: secretMessage } = trpc.auth.getSecretMessage.useQuery(
    undefined,
    { enabled: !!isSignedIn },
  );

  return (
    <div className="flex flex-col items-center justify-center gap-2 sm:flex-row">
      {isSignedIn && (
        <>
          <p className="text-center text-sm text-white sm:text-2xl">
            {secretMessage && <span>Hello, {secretMessage}</span>}
          </p>
          <div className="flex items-center justify-center">
            <UserButton
              appearance={{
                elements: {
                  userButtonAvatarBox: {
                    width: "3rem",
                    height: "3rem",
                  },
                },
              }}
            />
          </div>
        </>
      )}
      {!isSignedIn && (
        <button className="w-32 rounded-full bg-white text-center text-lg text-black">
          <Link href="/sign-in">Sign In</Link>
        </button>
      )}
      {!isSignedIn && (
        <button className="w-32 rounded-full bg-white text-center text-lg text-black">
          <Link href="/sign-up">Sign Up</Link>
        </button>
      )}
    </div>
  );
};
